In [5]:
%%bash 
cd /Users/asianzhang/Documents/GitHub/machine-learning-tone-generation
git add .
git commit --allow-empty-message -m "Started following along with tensorflow guide"
git push

[master 99c23fd] Started following along with tensorflow guide
 15 files changed, 120 insertions(+), 17 deletions(-)
 rename exercises/{tensorflow-test => tensorflow}/.ipynb_checkpoints/SmallCNNMNIST-checkpoint.ipynb (100%)
 rename exercises/{tensorflow-test => tensorflow}/.ipynb_checkpoints/SoftmaxRegressionMNIST-checkpoint.ipynb (100%)
 create mode 100644 exercises/tensorflow/.ipynb_checkpoints/TensorflowDevGuide-checkpoint.ipynb
 rename exercises/{tensorflow-test => tensorflow}/MNIST_data/t10k-images-idx3-ubyte.gz (100%)
 rename exercises/{tensorflow-test => tensorflow}/MNIST_data/t10k-labels-idx1-ubyte.gz (100%)
 rename exercises/{tensorflow-test => tensorflow}/MNIST_data/train-images-idx3-ubyte.gz (100%)
 rename exercises/{tensorflow-test => tensorflow}/MNIST_data/train-labels-idx1-ubyte.gz (100%)
 rename exercises/{tensorflow-test => tensorflow}/SmallCNNMNIST.ipynb (100%)
 rename exercises/{tensorflow-test => tensorflow}/SoftmaxRegressionMNIST.ipynb (100%)
 create mode 100644 exe

remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.        
remote: warning: See http://git.io/iEPt8g for more information.        
remote: warning: File project/audio/show.wav is 68.91 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB        
To https://github.com/asianzhang/machine-learning-tone-generation.git
   6a99bb2..99c23fd  master -> master


This notebook is used to type and run all of the examples in the tensorflow developer's guide at https://www.tensorflow.org/guide/.  
I'm starting at the low level APIs section because that will build a good foundation of tensorflow.

In [1]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import numpy as np
import tensorflow as tf

/Users/asianzhang/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
a = tf.constant(3.0, dtype=tf.float32)
b = tf.constant(4.0)
total = a + b
print(a)
print(b)
print(total)

Tensor("Const:0", shape=(), dtype=float32)
Tensor("Const_1:0", shape=(), dtype=float32)
Tensor("add:0", shape=(), dtype=float32)


In [3]:
sess = tf.Session()
print(sess.run(total))

7.0


In [4]:
print(sess.run({'ab':(a,b), 'total':total}))

{'ab': (3.0, 4.0), 'total': 7.0}


In [5]:
vec = tf.random_uniform(shape=(3,))
out1 = vec + 1
out2 = vec + 2
print(sess.run(vec))
print(sess.run(vec))
print(sess.run((out1, out2)))

[0.5552715  0.82778287 0.16398191]
[0.18297005 0.36957097 0.02147436]
(array([1.9025633, 1.7681226, 1.6356463], dtype=float32), array([2.9025633, 2.7681227, 2.6356463], dtype=float32))


In [6]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = x + y

In [7]:
print(sess.run(z, feed_dict={x: 3, y: 4.5}))
print(sess.run(z, feed_dict={x: [1, 3], y: [2, 4]}))

7.5
[3. 7.]


In [8]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]
slices = tf.data.Dataset.from_tensor_slices(my_data)
next_item = slices.make_one_shot_iterator().get_next()
next_next_item = slices.make_one_shot_iterator().get_next()

while True:
    try:
        print(sess.run(next_item))
        print(sess.run(next_next_item))
    except tf.errors.OutOfRangeError:
        break

[0 1]
[0 1]
[2 3]
[2 3]
[4 5]
[4 5]
[6 7]
[6 7]


In [9]:
r = tf.random_normal([10,3])
dataset = tf.data.Dataset.from_tensor_slices(r)
iterator = dataset.make_initializable_iterator()
next_row = iterator.get_next()

sess.run(iterator.initializer)
while True:
    try:
        print(sess.run(next_row))
    except tf.errors.OutOfRangeError:
        break

[-0.2548724  -0.61710674  0.8742846 ]
[ 0.4737459 -0.2835505  1.5249403]
[0.4185999  0.77723724 1.0179555 ]
[ 0.29605815  2.6402931  -0.52688533]
[ 1.212969  -0.3798886 -0.2694044]
[-0.11884152 -0.6604804   0.9200833 ]
[-0.10874021 -0.03746685 -1.8622037 ]
[ 0.38028434 -1.4052985   1.7909656 ]
[ 0.61951166 -0.57201856 -1.0136366 ]
[ 0.15401755 -0.97155756  1.5493947 ]


In [10]:
x = tf.placeholder(tf.float32, shape=[None, 3])
linear_model = tf.layers.Dense(units=1)
y = linear_model(x)

In [11]:
init = tf.global_variables_initializer()
sess.run(init)

In [12]:
print(sess.run(y, {x: [[1, 2, 3], [4, 5, 6]]}))

[[0.631511 ]
 [1.3439577]]


In [15]:
features = {
    'sales': [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list('department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [16]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
sess.run((var_init, table_init))
print(sess.run(inputs))

[[ 1.  0.  5.]
 [ 1.  0. 10.]
 [ 0.  1.  8.]
 [ 0.  1.  9.]]


In [18]:
x = tf.constant([[1], [2], [3], [4]], dtype=tf.float32)
y_true = tf.constant([[0], [-1], [-2], [-3]], dtype=tf.float32)

linear_model = tf.layers.Dense(units=1)

y_pred = linear_model(x)
loss = tf.losses.mean_squared_error(labels=y_true, predictions=y_pred)

optimizer = tf.train.GradientDescentOptimizer(0.01)
train = optimizer.minimize(loss)

init = tf.global_variables_initializer()

sess = tf.Session()
sess.run(init)
for i in range(100):
    _, loss_value = sess.run((train, loss))
    print(loss_value)
    
print(sess.run(y_pred))

14.008687
9.820284
6.9134436
4.895854
3.4953012
2.5228996
1.8475876
1.378423
1.0523031
0.82544225
0.6674588
0.5572711
0.48025143
0.42624968
0.3882228
0.36128402
0.34204233
0.32814467
0.31795847
0.31035087
0.3045355
0.29996717
0.29626727
0.29317304
0.2905023
0.28812855
0.2859639
0.2839475
0.28203708
0.2802032
0.2784254
0.2766897
0.27498603
0.27330768
0.27164996
0.2700093
0.26838347
0.26677096
0.26517048
0.26358128
0.2620027
0.26043433
0.258876
0.25732732
0.25578824
0.25425848
0.252738
0.2512267
0.24972454
0.24823137
0.24674714
0.24527183
0.24380535
0.24234763
0.2408987
0.23945841
0.23802666
0.23660359
0.23518893
0.2337828
0.23238505
0.23099563
0.22961453
0.22824174
0.22687711
0.22552063
0.22417228
0.22283201
0.22149971
0.22017542
0.21885903
0.21755049
0.21624978
0.2149569
0.21367167
0.21239413
0.2111243
0.20986201
0.20860733
0.20736009
0.20612031
0.20488794
0.20366295
0.20244527
0.20123486
0.2000317
0.19883578
0.19764695
0.19646527
0.19529067
0.19412301
0.19296241
0.19180869
0.19066194
